a= 10
b = 2
puts "a = #{a}"
puts "b = #{b}"
puts "a < b = #{a<b}"
puts "a > b = #{a>b}"
puts "a <= b = #{a<=b}"
puts "a >= b = #{a<=b}"
puts "a == b = #{a==b}"	
puts "false && false = #{false && false}"
puts "true && true = #{true && true}"
puts "true && false = #{true && false}"
puts "false || false = #{false || false}"
puts "true || true = #{true || true}"
puts "true || false = #{true || false}"
